USE mocktpo;

DROP TABLE IF EXISTS MT_USER;
CREATE TABLE MT_USER (
  MT_ID       BIGINT PRIMARY KEY AUTO_INCREMENT,
  MT_EMAIL    VARCHAR(255) NOT NULL,
  MT_PASSCODE CHAR(32)     NOT NULL
);

DROP TABLE IF EXISTS MT_LICENSE;
CREATE TABLE MT_LICENSE (
  MT_ID              BIGINT PRIMARY KEY AUTO_INCREMENT,
  MT_PRODUCT         VARCHAR(8)   NOT NULL,
  MT_EDITION         VARCHAR(16)  NOT NULL,
  MT_VERSION         VARCHAR(8)   NOT NULL,
  MT_ACTIVATION_CODE CHAR(32)     NOT NULL,
  MT_EMAIL           VARCHAR(255) NOT NULL,
  MT_HARDWARE        VARCHAR(255),
  MT_VALID_THROUGH   VARCHAR(8)   NOT NULL
);