USE mocktpo;

DROP TABLE IF EXISTS MT_USER;
CREATE TABLE MT_USER (
  MT_ID       BIGINT PRIMARY KEY AUTO_INCREMENT,
  MT_EMAIL    VARCHAR(255) NOT NULL,
  MT_PASSCODE CHAR(32)     NOT NULL
);

DROP TABLE IF EXISTS MT_ORDER;
CREATE TABLE MT_ORDER (
  MT_ID              BIGINT PRIMARY KEY AUTO_INCREMENT,
  MT_ORDER_NUMBER    CHAR(17)     NOT NULL,
  MT_PID             INT          NOT NULL,
  MT_EMAIL           VARCHAR(255) NOT NULL,
  MT_PAYMENT_TYPE    INT          NOT NULL,
  MT_PRICE           DOUBLE       NOT NULL,
  MT_STATUS          INT          NOT NULL,
  MT_ACTIVATION_CODE CHAR(32),
  MT_HARDWARE        VARCHAR(255)
);
